Add service account option
PrivateBin/helm-chart pull request #29
Opened 2020-09-18 16:37 UTC by quizy101

The chart does not support the use of service accounts. This feature is needed is some security contexts where API access to these resources may need to be limited.

I've set the default for `.Values.serviceAccount.create` to `false` to prevent any migrations for other users. Also, it will use the service account `default` on new installs just like it does now when set to `false`.

2020-09-22 15:28 UTC, bdashrad requested changes
looks good, but update the minor version number instead since we're adding features.

2020-09-22 15:28 UTC, bdashrad commented on privatebin/Chart.yaml
> +version: 0.5.3
```suggestion
version: 0.6.0
```

2020-09-22 17:36 UTC, bdashrad approved these changes

2020-09-22 17:36 UTC, merged

2020-09-22 23:55 UTC, jj0b commented
@quizy101 

Since this was merged today ArgoCD is no longer able to sync privatebin in my cluster.

```
GROUP  KIND        NAMESPACE   NAME                STATUS     HEALTH   HOOK  MESSAGE
apps   Deployment  privatebin  privatebin          OutOfSync  Missing        error validating data: ValidationError(Deployment.spec): unknown field "serviceAccountName" in io.k8s.api.apps.v1.DeploymentSpec
```

Is there something I need to update to accommodate this change?

2020-09-23 02:05 UTC, quizy101 commented
@jj0b I have a fix at #30 hopefully these changes can get merged quickly. Sorry for the confusion.

2020-09-23 14:36 UTC, jj0b commented
@quizy101 no worries. Thanks!

2020-09-23 19:12 UTC, jj0b commented
@quizy101 confirmed working. :-) Cheers!