add security context that we recommend for the image
PrivateBin/helm-chart pull request #32
Opened 2020-10-01 19:23 UTC by elrido

This is an untested change, that I hope will not break any existing setup. I would expect that k8s does run the process as specified in the container with the non-root user ID already and therefore the data gets owned accordingly, but as discussed in #31 it could be made explicit.

2020-10-02 05:38 UTC, bdashrad commented
I will review and test this tomorrow at work

2020-10-02 20:39 UTC, bdashrad requested changes
We may want to consider wrapping the `securityContext` block in a conditional, default off for now, until we release a version tagged docker image to reduce risk of hitting any edge cases.

We also should make this change to the StatefulSet

2020-10-02 20:39 UTC, bdashrad commented on privatebin/Chart.yaml
> +version: 0.6.2
I think we should go to 0.7.0 here since we have chance at breaking configs with security context changes
```suggestion
version: 0.7.0
```

2020-10-02 20:39 UTC, bdashrad commented on privatebin/templates/deployment.yaml
> +            readOnlyRootFilesystem: True
we should probably also explicitly add these.

```suggestion
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
```

https://kubernetes.io/docs/concepts/policy/pod-security-policy/

2020-10-03 08:47 UTC, elrido commented
Ok, I've created a tag "1.3.4-alpine3.12-k8s-sec-context" on the image repo, which got [auto-built and published to the docker hub](https://hub.docker.com/layers/privatebin/nginx-fpm-alpine/1.3.4-alpine3.12-k8s-sec-context/images/sha256-2fadf00923466f58bf376930007d68ed72e55b29e6fa1845d5685096cf5a21d9?context=explore). Would I now need to change the Chart.yaml's appversion to this tag or would you prefer to have the conditional in place anyway?
https://github.com/PrivateBin/helm-chart/blob/109a3c5339eb60405b74114d8a603f969649a506/privatebin/Chart.yaml#L3

2020-10-05 15:42 UTC, bdashrad commented
I need to think about how to do this properly in the stateful set so we don't break anyone using persistent volumes for storage.

2020-10-06 05:13 UTC, elrido commented
Yes, lets better be careful with this change.

Don't know if this is helpful or not: For that k8s setup with an NFS backed persistent volume I had to use an init container in the deployment to set up the permissions (as in the [example for the image's README)](https://github.com/PrivateBin/docker-nginx-fpm-alpine#kubernetes-deployment). Maybe if it got used to recursively update the permissions?

```
      initContainers:
      - name: {{ .Chart.Name }}-permissions
        image: privatebin/chown:1.31.1-musl-1.1.24-r9
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['-R', '65534:82', '/mnt']
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /mnt
          name: storage
          readOnly: False
```
Note: The [image mentioned above](https://hub.docker.com/r/privatebin/chown) contains only the chown binary built from busybox.

2020-10-06 13:48 UTC, bdashrad commented
That seems to be the common way to deal with file permissions in this situation. For example: https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-statefulset.yaml#L317

2020-12-07 13:31 UTC, Punkoivan commented
Hello there.
I would add fsGroup and set to 82.
Without this it breaks on EKS with gp2 as PV and StatefulSet as a kind.

Also ReadWriteMany is not allowed mode within gp2, so made it as a variable in values.
Submitted PR  #37 
Would be happy to adjust that to fit this one.

Thanks!

2021-11-04 19:03 UTC, merged